[package]
name = "aether_core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["tokio", "macros"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.52.3", features = ["full"] }
toml = "1.1.2"
thiserror = "2.0.18"
surrealdb = "3.1.4"
# facets
aether_cache = { path = "../cache" }
aether_organization = { path = "../organization" }
aether_orm = { path = "../orm" }
aether_web = { path = "../web" }
aether_event_bus = { path = "../event_bus" }
log = "0.4.32"
directories = "6.0.0"

[dev-dependencies]
tempfile = "3"
