[package]
name = "aether"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = ["full"] }
clap = { version = "4.6.6", features = ["env", "derive", "string"] }
log = "0.4"
env_logger = "0.11"
surrealdb.workspace = true
thiserror = "2.0.20"
colored = "3"
# Aether modules
aether_core = { path = "../facets/core" }
aether_orm = { path = "../facets/orm" }
aether_storage = { path = "../facets/storage" }
aether_authentication = { path = "../facets/authentication" }
include_dir = "0.7.4"
directories = "6.0.0"
toml_edit = "0.25.15"
notify = "8"

[dev-dependencies]
tempfile.workspace = true
