[workspace]
name = "erp"
label = "Enterprise Resource Planner"
version = "0.1"
description = """
This is a software suite
"""
group = "erp_software"
icon = "./assets/erp.svg"


[[modules]]
name = "accounting"
path = "./accounting"
