[workspace]
name = "erp"
label = "Enterprise Resource Planner"
version = "0.1"
assets = "./assets"
description = """
This is a software suite
"""
group_label = "ERP Software Addons"
group_icon = "./assets/erp.svg"


[[modules]]
name = "accounting"
path = "./accounting"
