[package]
name = "aether_storage"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
object_store.workspace = true
thiserror = "2.0.20"

[dev-dependencies]
object_store = { workspace = true }
tokio = { version = "1.53.1", features = ["macros", "rt"] }
