[workspace]
name = "base"
version = "1.0"
aether_version = "0.1"
label = "Base Plugin"
description = "The base description"
long_description = """
The base description
"""

# plugin_files = "./plugins.toml"
